In [1]:
import numpy as np
import pandas as pd

In [2]:
ihdp_results = pd.read_csv('ihdp_CATE_PEHE.csv')

In [6]:
round(ihdp_results.groupby(['gen_type', 'learner']).mean(), 3)

/tmp/ipykernel_734466/2785684816.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(ihdp_results.groupby(['gen_type', 'learner']).mean(), 3)

                   rmse
gen_type learner
arf      DRNet()  2.918
         PWNet()  3.470
         RANet()  2.736
         SNet()   3.171
         TNet()   2.737
ctgan    DRNet()  3.662
         PWNet()  5.523
         RANet()  2.512
         SNet()   3.028
         TNet()   2.551
ddpm     DRNet()  2.680
         PWNet()  3.846
         RANet()  1.957
         SNet()   2.498
         TNet()   2.004
nflow    DRNet()  4.253
         PWNet()  6.346
         RANet()  3.909
         SNet()   4.826
         TNet()   3.822
real     DRNet()  0.704
         PWNet()  1.750
         RANet()  0.559
         SNet()   1.549
         TNet()   0.634
tvae     DRNet()  2.764
         PWNet()  4.460
         RANet()  2.695
         SNet()   3.796
         TNet()   2.756

In [7]:
round(ihdp_results.groupby(['gen_type', 'learner']).std(),3)

/tmp/ipykernel_734466/2934920463.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(ihdp_results.groupby(['gen_type', 'learner']).std(),3)

                   rmse
gen_type learner
arf      DRNet()  0.601
         PWNet()  0.792
         RANet()  0.565
         SNet()   0.726
         TNet()   0.533
ctgan    DRNet()  2.640
         PWNet()  4.356
         RANet()  0.843
         SNet()   0.348
         TNet()   0.836
ddpm     DRNet()  1.073
         PWNet()  0.926
         RANet()  0.310
         SNet()   0.396
         TNet()   0.402
nflow    DRNet()  1.076
         PWNet()  2.653
         RANet()  1.259
         SNet()   0.841
         TNet()   1.284
real     DRNet()    NaN
         PWNet()    NaN
         RANet()    NaN
         SNet()     NaN
         TNet()     NaN
tvae     DRNet()  0.358
         PWNet()  0.230
         RANet()  0.471
         SNet()   0.362
         TNet()   0.533

In [8]:
acic_results = pd.read_csv('acic_CATE_PEHE.csv')

In [9]:
round(acic_results.groupby(['gen_type', 'learner']).mean(), 3)

/tmp/ipykernel_734466/1882807954.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(acic_results.groupby(['gen_type', 'learner']).mean(), 3)

                    rmse
gen_type learner
arf      DRNet()   4.376
         PWNet()   6.644
         RANet()   4.344
         TNet()    4.320
ctgan    DRNet()   4.430
         PWNet()   4.995
         RANet()   4.768
         TNet()    5.280
ddpm     DRNet()   7.874
         PWNet()   5.425
         RANet()  10.835
         TNet()   10.878
nflow    DRNet()   4.812
         PWNet()   5.340
         RANet()   5.145
         TNet()    4.818
real     DRNet()   2.445
         PWNet()   5.084
         RANet()   1.824
         TNet()    2.033
tvae     DRNet()   4.218
         PWNet()   5.439
         RANet()   4.354
         TNet()    4.490

In [10]:
round(acic_results.groupby(['gen_type', 'learner']).std(), 3)

/tmp/ipykernel_734466/2199754328.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(acic_results.groupby(['gen_type', 'learner']).std(), 3)

                   rmse
gen_type learner
arf      DRNet()  0.723
         PWNet()  1.941
         RANet()  0.403
         TNet()   0.426
ctgan    DRNet()  0.714
         PWNet()  1.185
         RANet()  0.362
         TNet()   0.567
ddpm     DRNet()  4.179
         PWNet()  1.198
         RANet()  7.389
         TNet()   6.220
nflow    DRNet()  0.584
         PWNet()  0.644
         RANet()  0.414
         TNet()   0.403
real     DRNet()    NaN
         PWNet()    NaN
         RANet()    NaN
         TNet()     NaN
tvae     DRNet()  0.078
         PWNet()  1.669
         RANet()  0.328
         TNet()   0.502

In [4]:
ihdp_standard_metrics = pd.read_csv('ihdp_standard_metrics.csv', index_col = 0)

In [12]:
ihdp_standard_metrics['gen'] = [i.split('_')[0] for i in ihdp_standard_metrics['dataset']]

In [24]:
round(ihdp_standard_metrics[ihdp_standard_metrics['metric']=='marginal'].groupby('gen').mean().sort_values(by='result'), 3)

/tmp/ipykernel_1027210/3429467271.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(ihdp_standard_metrics[ihdp_standard_metrics['metric']=='marginal'].groupby('gen').mean().sort_values(by='result'), 3)

       result
gen
tvae    0.900
ddpm    0.915
ctgan   0.946
nflow   0.971
arf     0.989

In [25]:
round(ihdp_standard_metrics[ihdp_standard_metrics['metric']=='delta_precision_alpha_OC'].groupby('gen').mean().sort_values(by='result'),3)

/tmp/ipykernel_1027210/175794599.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(ihdp_standard_metrics[ihdp_standard_metrics['metric']=='delta_precision_alpha_OC'].groupby('gen').mean().sort_values(by='result'),3)

       result
gen
nflow   0.231
arf     0.353
tvae    0.431
ctgan   0.432
ddpm    0.516

In [26]:
round(ihdp_standard_metrics[ihdp_standard_metrics['metric']=='delta_coverage_beta_OC'].groupby('gen').mean().sort_values(by='result'), 3)

/tmp/ipykernel_1027210/3966152869.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(ihdp_standard_metrics[ihdp_standard_metrics['metric']=='delta_coverage_beta_OC'].groupby('gen').mean().sort_values(by='result'), 3)

       result
gen
nflow   0.162
arf     0.254
ctgan   0.292
tvae    0.319
ddpm    0.335

In [29]:
acic_standard_metrics = pd.read_csv('acic_standard_metrics.csv')

In [31]:
acic_standard_metrics['gen'] = [i.split('_')[0] for i in acic_standard_metrics['dataset']]

In [34]:
round(acic_standard_metrics[acic_standard_metrics['metric']=='marginal'].groupby('gen').mean().sort_values(by='result'), 3)

/tmp/ipykernel_1027210/2594636950.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(acic_standard_metrics[acic_standard_metrics['metric']=='marginal'].groupby('gen').mean().sort_values(by='result'), 3)

       result
gen
ddpm    0.623
tvae    0.917
nflow   0.920
ctgan   0.968
arf     0.984

In [35]:
round(acic_standard_metrics[acic_standard_metrics['metric']=='delta_precision_alpha_OC'].groupby('gen').mean().sort_values(by='result'), 3)

/tmp/ipykernel_1027210/1207424363.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(acic_standard_metrics[acic_standard_metrics['metric']=='delta_precision_alpha_OC'].groupby('gen').mean().sort_values(by='result'), 3)

       result
gen
ddpm    0.136
nflow   0.693
arf     0.781
ctgan   0.863
tvae    0.966

In [36]:
round(acic_standard_metrics[acic_standard_metrics['metric']=='delta_coverage_beta_OC'].groupby('gen').mean().sort_values(by='result'), 3)

/tmp/ipykernel_1027210/1585378624.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(acic_standard_metrics[acic_standard_metrics['metric']=='delta_coverage_beta_OC'].groupby('gen').mean().sort_values(by='result'), 3)

       result
gen
ddpm    0.002
nflow   0.325
arf     0.432
ctgan   0.439
tvae    0.493

In [65]:
ihdp_flip = pd.read_csv('ihdp_rate_of_flipping.csv', header =0, names = ['name', 'rate'])

In [66]:
ihdp_flip['gen'] = [i.split('_')[0] for i in ihdp_flip['name']]

In [67]:
ihdp_flip['learner'] = [i[-6:] for i in ihdp_flip['name']]

In [68]:
round(ihdp_flip.groupby(['gen', 'learner']).mean(), 3)

/tmp/ipykernel_1027210/988103298.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(ihdp_flip.groupby(['gen', 'learner']).mean(), 3)

                      rate
gen         learner
arf         ANet()   0.166
            RNet()   0.216
            SNet()   0.241
            TNet()   0.164
            WNet()   0.390
ctgan       ANet()   0.118
            RNet()   0.196
            SNet()   0.204
            TNet()   0.138
            WNet()   0.362
ddpm        ANet()   0.065
            RNet()   0.113
            SNet()   0.056
            TNet()   0.063
            WNet()   0.337
nflow       ANet()   0.383
            RNet()   0.429
            SNet()   0.450
            TNet()   0.377
            WNet()   0.674
realDRNet() RNet()   0.004
realPWNet() WNet()   0.115
realRANet() ANet()   0.007
realSNet()  SNet()   0.011
realTNet()  TNet()   0.011
tvae        ANet()   0.173
            RNet()   0.179
            SNet()   0.366
            TNet()   0.176
            WNet()   0.546

In [70]:
acic_flip = pd.read_csv('acic_rate_of_flipping.csv', header =0, names = ['name', 'rate'])

In [71]:
acic_flip['gen'] = [i.split('_')[0] for i in acic_flip['name']]

In [72]:
acic_flip['learner'] = [i.split('_')[-1] for i in acic_flip['name']]

In [74]:
round(acic_flip.groupby(['gen', 'learner']).mean(), 3)

/tmp/ipykernel_1027210/3612201374.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  round(acic_flip.groupby(['gen', 'learner']).mean(), 3)

                rate
gen   learner
arf   DRNet()  0.310
      PWNet()  0.595
      RANet()  0.262
      TNet()   0.265
ctgan DRNet()  0.321
      PWNet()  0.391
      RANet()  0.328
      TNet()   0.420
ddpm  DRNet()  0.479
      PWNet()  0.482
      RANet()  0.634
      TNet()   0.644
nflow DRNet()  0.459
      PWNet()  0.643
      RANet()  0.579
      TNet()   0.391
real  DRNet()  0.070
      PWNet()  0.369
      RANet()  0.053
      TNet()   0.055
tvae  DRNet()  0.234
      PWNet()  0.500
      RANet()  0.261
      TNet()   0.300